#!/bin/bash

if [[ ! -x "$(command -v go)" ]]; then
  echo >&2 "go runtime is required: https://golang.org/doc/install"
  exit 1
fi

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."

go test -count=1 -race -v $(go list ./... | grep -v -E '\/(vendor|examples)\/')
